name: Test and lint

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    timeout-minutes: 1
    runs-on: ubuntu-latest
    steps:
      - name: Checkout GitHub Action
        uses: actions/checkout@v4

      - name: Install the latest version of ruff
        uses: astral-sh/ruff-action@v3

      - name: Check formatting
        run: ruff format --check

      - name: Check linting
        run: ruff check

  test:
    name: test
    timeout-minutes: 5
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          - '3.10'
          - '3.11'
          - '3.12'
          - '3.13'
    steps:
      - name: Checkout GitHub Action
        uses: actions/checkout@v4

      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@v5
        with:
          python-version: ${{ matrix.python-version }}
          enable-cache: true
          cache-dependency-glob: uv.lock

      - name: Install project dependencies
        run: uv sync --frozen --group test

      - name: Run tests
        run: uv run pytest --cov
